### ISSUE TITLE
bitclockers not showing all results

### ISSUE THREAD

**Issue by rampa069** [jakubwolny/mining-monitor#5]
only hashrate, workers and payout are showing.

**Comment by rampa069** [comment]
diff --git a/background.html b/background.html
index 7ab7fa6..d6445ab 100644
--- a/background.html
+++ b/background.html
@@ -286,7 +286,9 @@
                 return text.slice(text.indexOf("Change")-32, text.indexOf("Change")); 
             },
             fieldsMap: {
-                confirmed_reward: "dashboard"  
-                confirmed_reward: "balance",
-                estimated_reward: "estimatedearnings",
-                payout: "payout"
           },
           process: function(){
               this.data.workers_alive = 0;
  @@ -310,7 +312,8 @@
               return element.attr('href') ? element.attr('href').slice(-32) : '';
           },
           fieldsMap: {
-                confirmed_reward: "balance"  
-                confirmed_reward: "balance",
-                estimated_reward: "estimatedearnings: "
           },
           process: function(){
               this.data.workers_all = 0;

**Comment by jakubwolny** [comment]
I have updated the extension with your code (and some other fixes) - thanks for reporting the issue.
But in the future please just fork the repo and make pull request instead of displaying diff ;)
